const NAME_OR_PASSWORD_IS_REQUIRED = -1001
const NAME_IS_ALREADY_EXISTS = -1002
const USER_IS_NOT_EXISTS = -1003
const PASSWORD_INCORRECT = -1004
const UNAUTHORIZED = -1005
const OPERATION_WITHOUT_PERMISSTION = -1006

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  NAME_IS_ALREADY_EXISTS,
  USER_IS_NOT_EXISTS,
  PASSWORD_INCORRECT,
  UNAUTHORIZED,
  OPERATION_WITHOUT_PERMISSTION
}
